### PR TITLE
Page/blog page

### PR DESCRIPTION
**Pull request by EgoEris**
## Description

Implementation of News page
* added in News page
* Users are able to view pdfs of news
* Nav bar modified to include news

## Screenshots

image
image

### CODE REVIEW

**Comment by fung-alvin** [comment]
image

image

Just some formatting and loading issues to bring up, not sure if you're aware.

Also, strangely I couldn't pull the commits before, and had to run
`git config http.version HTTP/1.1`
before I could pull. Did you have similar experience?

**Comment by EgoEris** [comment]
> image image
> 
> Just some formatting and loading issues to bring up, not sure if you're aware.
> 
> Also, strangely I couldn't pull the commits before, and had to run `git config http.version HTTP/1.1` before I could pull. Did you have similar experience?

For the formatting issues is it the misalignment of the logo and the heading? I'll take a look at it - think it's an issue with laptop screens as it looks alright on larger monitors

For the pdf issue, what happens when you press the open button? And what browser are you using? I

for pulling, i didn't experience any issues with this - do you know what error popped up?

**Comment by fung-alvin** [comment]
Formatting was more so for the contact us button. On my laptop, the text is not on a single line.

When I click into the open button, it downloads the PDF directly. Not sure if that’s what was intended, or simply a preview style.

I’ll come back with a screenshot of the error in terminal.

**Comment by EgoEris** [comment]
the pdf section should be an embed - it'll depend on ur browser but you should be able it see it directly rather than needing to download

The contact us button is more squished due to the addition of the news tab, reckon i can either make it so that before the button becomes a 2 liner?

**Comment by EgoEris** [comment]
Hmmm perhaps it is an extension? I've tested on firefox, edge + chrome and it looks alright for me. If you want we can look further into the pdf issue, but I'm not able to recreate it so will probably need more details!

also fixed up the navbar issue:
image
^ Nav bar when viewport is 1920px wide

image

^ Nav bar when viewport is 1200px wide

image
^ Nav bar when viewport is 1024px wide (just before the navbar transforms into mobile view)

**Comment by fung-alvin** [comment]
Looks good now. I reckon we'll leave the preview issue for now - very minor anyways.

**Review by fung-alvin — APPROVED** [review]
Approved

**Comment by EgoEris** [comment]
Cheers! will wait for Ops to confirm if this is the version of the newsletter they want to host before merging

**Comment by viggy21** [comment]
I just tested it out and everything's working well on my end! 
image

**Comment by EgoEris** [comment]
Awesome cheers @viggy21!

**Pull request merged**
